git rm --cached .webassets-cache/
git rm --cached webassets-external/
git rm --cached .DS_Store
git rm --cached *.pyc
git rm --cached *.pyo
git rm --cached __pycache__
git rm --cached env
git rm --cached venv
git rm --cached *.env
git rm --cached env*
git rm --cached dist
git rm --cached *.egg
git rm --cached *.egg-info
git rm --cached *.sqlite
git rm --cached .idea
git rm --cached dump.rdb
git rm --cached .vscode/
git rm --cached .history/
git rm --cached config.env
git rm --cached *.db
git rm --cached LICENSE.txt
git rm --cached bad_README.txt
git rm --cached bad_Dockerfile
git rm --cached bad_Procfile.txt
git rm --cached bad_docker-compose.yml
git rm --cached bad_docs
git rm --cached bad_readme_media
